/**
 * The confirmed CUA surface (from the user-confirmed spec in this repo).
 * Used at runtime for self-checks and for generating the contract manifest and
 * API surface snapshots. `acceptance/contract.json` stays the independent input
 * and is never modified.
 */

export const CONFIRMED_SURFACE = {
  cua: ['getState', 'listBrowsers', 'getBrowser', 'createBrowserTab', 'getTab', 'listTabs'],
  browser: ['documentation', 'history', 'nameSession'],
  'browser.tabs': ['new', 'selected', 'list', 'get'],
  'browser.capabilities': ['list', 'get'],
  tab: [
    'getAXState',
    'getScreenshot',
    'getAXStateAndScreenshot',
    'paste',
    'click',
    'drag',
    'pressKey',
    'scroll',
    'selectText',
    'setValue',
    'typeText',
    'performSecondaryAction',
    'goto',
    'back',
    'forward',
    'reload',
    'close',
    'title',
    'url',
    'getJsDialog',
    'markDeliverable',
    'markHandoff',
  ],
  'tab.ax': [
    'get',
    'write',
    'click',
    'drag',
    'performSecondaryAction',
    'pressKey',
    'scroll',
    'selectText',
    'setValue',
    'typeText',
  ],
  'tab.playwright': [
    'goBack',
    'goForward',
    'evaluate',
    'locator',
    'getByRole',
    'getByText',
    'getByLabel',
    'getByPlaceholder',
    'getByTestId',
    'frameLocator',
    'waitForURL',
    'waitForLoadState',
    'waitForTimeout',
    'waitForEvent',
    'expectNavigation',
    'elementInfo',
    'elementScreenshot',
    'domSnapshot',
  ],
  locator: [
    'click',
    'dblclick',
    'fill',
    'type',
    'pressSequentially',
    'press',
    'setChecked',
    'check',
    'uncheck',
    'selectOption',
    'waitFor',
    'count',
    'all',
    'textContent',
    'innerText',
    'allTextContents',
    'getAttribute',
    'isVisible',
    'isEnabled',
    'evaluate',
    'evaluateAll',
    'locator',
    'first',
    'last',
    'nth',
    'and',
    'or',
    'filter',
    'getByRole',
    'getByText',
    'getByLabel',
    'getByPlaceholder',
    'getByTestId',
    'downloadMedia',
  ],
  frameLocator: [
    'locator',
    'frameLocator',
    'getByRole',
    'getByText',
    'getByLabel',
    'getByPlaceholder',
    'getByTestId',
  ],
  'tab.content': ['export', 'exportGsuite', 'exportYouTubeTranscript'],
  'tab.clipboard': ['read', 'readText', 'write', 'writeText'],
  'tab.dev': ['logs'],
  'tab.capabilities': ['list', 'get'],
  visibility: ['documentation', 'get', 'set'],
  viewport: ['documentation', 'set', 'reset'],
  pageAssets: ['documentation', 'list', 'bundle'],
  webmcp: ['documentation', 'fetchTools'],
  cdp: ['documentation', 'send', 'readEvents'],
};

export const REQUIRED_TAB_PROPERTIES = [
  'id',
  'ax',
  'playwright',
  'content',
  'clipboard',
  'dev',
  'capabilities',
];
export const FORBIDDEN_TAB_PROPERTIES = ['cua', 'dom_cua'];
export const REQUIRED_BROWSER_PROPERTIES = ['tabs', 'capabilities'];

export const EXTRA_SURFACE = {
  cua: [
    'nativeDocumentation',
    'listApps',
    'getApp',
    'launchApp',
    'listWindows',
    'getWindow',
    'getComputer',
  ],
  nativeApp: [
    'documentation',
    'windows',
    'getWindow',
    'waitForWindow',
    'getAXState',
    'getScreenshot',
    'getAXStateAndScreenshot',
    'getState',
    'click',
    'drag',
    'pressKey',
    'scroll',
    'setValue',
    'typeText',
    'performSecondaryAction',
    'activate',
    'close',
  ],
  tab: ['browserId', 'insertText'],
  locator: ['inputValue', 'setInputFiles'],
  webmcp: ['call'],
};

// The extension provider intentionally has a newer Codex-shaped surface than
// the user-confirmed IAB contract above. Keep it separate so adding Chrome
// interoperability does not silently redefine the IAB compatibility target.
export const EXTENSION_SURFACE = {
  browser: ['documentation', 'history', 'nameSession'],
  'browser.user': ['documentation', 'openTabs', 'claimTab'],
  'browser.tabs': ['new', 'selected', 'list', 'get', 'finalize'],
  tab: ['screenshot', 'cua', 'dom_cua'],
  'tab.cua': [
    'documentation',
    'move',
    'click',
    'write',
    'type',
    'key',
    'press',
    'scroll',
    'screenshot',
  ],
  'tab.dom_cua': ['documentation', 'get_visible_dom'],
};

export const UNAVAILABLE_SURFACES = [
  {
    id: 'extension-backend',
    surface: ['browsers.type=extension'],
    status: 'conditional',
    reason:
      'The packaged Google Chrome extension + Native Messaging host must complete a local hello handshake.',
    behavior:
      'No extension browser is advertised until connected; raw CDP endpoints are never mislabeled as extension browsers.',
  },
  {
    id: 'webmcp-native',
    surface: ['webmcp.native'],
    status: 'conditional',
    reason:
      'Actual native document.modelContext execution was not available in the tested Google Chrome build; a clearly labeled local shim was used in real fixture tests.',
    behavior:
      'fetchTools() reports mode "native" only when the browser really exposes it; otherwise "shim" or "none" with an unavailableReason.',
  },
  {
    id: 'gsuite-auth',
    surface: ['content.exportGsuite'],
    status: 'implemented-untested-credentials',
    reason: 'No Google credentials are available in this environment.',
    behavior:
      'URL validation + native export endpoints are implemented; without a signed-in profile the call returns auth_required.',
  },
];
